### ISSUE TITLE
Нужна помощь с лабами

### ISSUE THREAD

**Issue by myg1tsh1t** [Sprutoplut/OptimizationNumber1#1]
Линейное\нелинейное программирование\методы оптимизации\задачи сетевого планирования и тп.
Если есть желание - договоримся.
Тг al1no1

**Comment by Sprutoplut** [comment]
Я лабами больше не занимаюсь, только могу посоветовать кого-нибудь, у кого времени побольше

**Comment by myg1tsh1t** [comment]
Был бы рад. Ситуация патовая.

**Comment by Sprutoplut** [comment]
Из какого города и универ если не секрет ?

**Comment by myg1tsh1t** [comment]
Секрет) Но точно не из Уфы, у нас время разное. Примерное задание на лабы, если знаешь человека который поможет:
Лабораторная работа №2. Задачи подсистемы ТПП
1.	Задача сетевого планирования проекта с учетом вероятностного времени выполнения отдельных работ.
Лабораторная работа №3. Задачи подсистемы ОУП
1.	Задача Джонсона для 2-х и 3-х станков.

Вообще в тг пойти можем

**Comment by Sprutoplut** [comment]
У тебя есть лаба в текстовом виде, файл ? Отправь

**Comment by myg1tsh1t** [comment]
Все есть, и примеры, и лекции. Просто не хочется писать это все в открытом пространстве. Честно, лучше на почту или еще куда то.
docs .google .com/document/d/1-zo2TbjazPMY85lRQG2DnMv0PkRJgwmJ

**Comment by Sprutoplut** [comment]
Мои не смогут сделать, а я просто не успеваю, извини(

**Comment by myg1tsh1t** [comment]
Эх, жаль. 
У меня срок до января если что, может даже позже, если дадут в другом семестре сдавать. Если будет время\потянешь - пиши. Мне главное качественная работа.

**Comment by Sprutoplut** [comment]
У меня загрузка полная до конца января примерно, если дадут время до весны напиши, rus.galan@mail.ru
